In [4]:
import torch

In [5]:
a = torch.ones(3) # Build a 1-d tensor and fill one in it.
a

tensor([1., 1., 1.])

In [6]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [7]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [8]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [10]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
points.shape

torch.Size([3, 2])

In [12]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
points[0]

tensor([0., 0.])

# Index  tensor

In [14]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [15]:
some_list[:]
some_list[1:4]
some_list[1:]

[1, 2, 3, 4, 5]

In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [17]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [18]:
# Lines besides the first line, the first column
points[1:, 0]

tensor([5., 2.])

# Nameing a tensor

In [19]:
img_t = torch.randn(3, 5, 5) # Shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
img_t

tensor([[[-0.0905, -0.4903, -1.3038, -0.8896, -1.2796],
         [ 1.3463,  0.1972, -0.1853,  0.7096,  0.7803],
         [-0.9676,  0.8480, -0.2113,  0.2768,  0.8033],
         [ 0.0649,  1.0050, -0.4295,  0.3188, -0.6243],
         [ 0.2493, -0.0579,  0.8300,  0.2460,  0.4223]],

        [[-0.4302,  0.5879,  0.1404, -0.3969, -0.9986],
         [ 0.5385,  0.6507, -0.8788,  0.3659,  0.6484],
         [-0.2459, -1.6618,  1.5607, -0.0815, -0.0307],
         [-0.9663,  2.1621,  0.4497, -0.2195, -1.1849],
         [-0.2782, -0.8164,  0.4416,  1.2737, -0.4922]],

        [[ 0.1381,  0.4352,  1.3895,  0.2413,  0.4484],
         [ 0.2140,  0.2403, -1.2674, -0.3489, -0.5908],
         [-1.3496, -1.6443, -2.1670, -0.8901, -2.1273],
         [ 1.9505, -0.1283, -1.8012, -1.0908, -0.7135],
         [-0.5097,  0.2747,  1.2505, -0.1223,  0.3640]]])

In [20]:
batch_t = torch.randn(2, 3, 5, 5) # Shape(batch, channels, rows, columns)
batch_t

tensor([[[[-2.1007, -1.5652, -2.0181, -0.2759, -1.5957],
          [ 0.9648, -0.2170, -0.0740, -0.0149, -0.1177],
          [-0.9254, -0.2406, -0.6306,  0.6397, -0.2801],
          [-1.2200, -0.3138,  1.1677,  0.9057, -0.1552],
          [ 2.5715,  0.1823, -0.3827, -2.7412, -0.3039]],

         [[ 1.3861, -1.4387,  0.2010,  0.4517, -1.2188],
          [ 0.3689,  2.1002, -1.6495, -0.3658, -0.3651],
          [ 0.9747, -1.0026, -1.5662, -1.0754,  0.3262],
          [ 0.1059, -0.5591,  1.8985,  1.8190, -0.6675],
          [-0.8697,  1.6836, -1.5857, -0.3766, -0.4993]],

         [[ 1.0357,  0.1310,  0.0539, -1.2120,  1.0420],
          [-0.8515,  0.0986, -1.0086,  1.4893,  0.2035],
          [-0.8220, -0.7517, -1.3974,  0.4714, -0.2777],
          [ 1.7542,  0.6619,  0.1246, -0.6129,  1.1925],
          [-1.1775, -0.4835, -0.4101, -1.5934,  1.4918]]],


        [[[ 0.1373, -0.7405, -1.9968, -1.2791,  1.5796],
          [ 3.2071, -1.2705, -0.9916,  0.2986, -0.3604],
          [ 1.0445, -0.

In [21]:
img_gray_navie = img_t.mean(-3) # Color channel always begins with the 3 position from the last.

In [22]:
batch_gray_navie = batch_t.mean(-3)
img_gray_navie.shape, batch_gray_navie.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [39]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weigths)
batch_weights = (batch_t * unsqueezed_weights) 
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))